# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 16, 44, 20, 795293)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 9, 16, 44, 20, 795339)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 16, 44, 20, 795322)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 16, 44, 20, 794248)),
        ),
    ]
